### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by looselycoupled** [SoftwareDefinedBuildings/btrdb#19]
I was hoping to evaluate btrdb but ran into difficulty during installation while following the instructions in the README in the master branch.  The instructions say to execute:

    go get github.com/SoftwareDefinedBuildings/btrdb/server

However, this results in the error:

    package github.com/SoftwareDefinedBuildings/btrdb/server: cannot find package "github.com/SoftwareDefinedBuildings/btrdb/server" in any of:
	/usr/lib/go/src/github.com/SoftwareDefinedBuildings/btrdb/server (from $GOROOT)

While I'm not a Go developer it seems as if the installation is expecting a `server` folder under the root which is no longer available and I'm unsure how to continue.  Using the alternate installation method also appears to error as shown:

    $ go get -d ./... && go install ./btrdbd
    package ./btrdb
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bstore: use of internal package not allowed
    package ./btrdb/btrdbd
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bstore: use of internal package not allowed
    package ./btrdb/internal/bstore
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bprovider: use of internal package not allowed
    package ./btrdb/internal/bstore
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/cephprovider: use of internal package not allowed
    package ./btrdb/internal/bstore
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/fileprovider: use of internal package not allowed
    package ./btrdb/internal/cephprovider
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bprovider: use of internal package not allowed
    package ./btrdb/internal/fileprovider
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bprovider: use of internal package not allowed
    package ./btrdb/qtree
    	imports github.com/SoftwareDefinedBuildings/btrdb/internal/bstore: use of internal package not allowed
    gocode/src/github.com/stretchr/graceful/tests/main.go:7:2: cannot find package "github.com/codegangsta/negroni" in any of:
    	/usr/lib/go/src/github.com/codegangsta/negroni (from $GOROOT)
    	/home/allen/gocode/src/github.com/codegangsta/negroni (from $GOPATH)
    gocode/src/github.com/stretchr/graceful/tests/main.go:8:2: cannot find package "github.com/tylerb/graceful" in any of:
    	/usr/lib/go/src/github.com/tylerb/graceful (from $GOROOT)
    	/home/allen/gocode/src/github.com/tylerb/graceful (from $GOPATH)
    gocode/src/golang.org/x/net/html/charset/charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
    	/usr/lib/go/src/golang.org/x/text/encoding (from $GOROOT)
    	/home/allen/gocode/src/golang.org/x/text/encoding (from $GOPATH)
    gocode/src/golang.org/x/net/html/charset/charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
    	/usr/lib/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
    	/home/allen/gocode/src/golang.org/x/text/encoding/charmap (from $GOPATH)
    gocode/src/golang.org/x/net/html/charset/charset.go:22:2: cannot find package "golang.org/x/text/encoding/htmlindex" in any of:
    	/usr/lib/go/src/golang.org/x/text/encoding/htmlindex (from $GOROOT)
    	/home/allen/gocode/src/golang.org/x/text/encoding/htmlindex (from $GOPATH)
    gocode/src/golang.org/x/net/html/charset/charset.go:23:2: cannot find package "golang.org/x/text/transform" in any of:
    	/usr/lib/go/src/golang.org/x/text/transform (from $GOROOT)
    	/home/allen/gocode/src/golang.org/x/text/transform (from $GOPATH)
    gocode/src/golang.org/x/net/http2/h2i/h2i.go:38:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
    	/usr/lib/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
    	/home/allen/gocode/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
    gocode/src/gopkg.in/mgo.v2/dbtest/dbserver.go:13:2: cannot find package "gopkg.in/tomb.v2" in any of:
    	/usr/lib/go/src/gopkg.in/tomb.v2 (from $GOROOT)
    	/home/allen/gocode/src/gopkg.in/tomb.v2 (from $GOPATH)

This was using a clean install of Ubuntu 14.04, fully updated, with `librados-dev` and MongoDB already installed.  I found the FAST paper extremely interesting and was hoping someone could point me in the right direction.  Thanks

**Comment by gtfierro** [comment]
I believe `server` should be replaced with `btrdbd` in the URL. The README definitely needs an update

**Comment by looselycoupled** [comment]
Yup, I now have `btrdbd` in the bin folder and was able to use `-makedb`.  Thanks for you help

**Comment by immesys** [comment]
Sorry for that. I have a block of time in a few weeks for making a release of BTrDB with a bunch of new features, documentation and installation scripts, but until then it's a little rough

**Comment by immesys** [comment]
Also, you may find [the newly released btrdb-go bindings](https://github.com/SoftwareDefinedBuildings/btrdb-go) helpful if you are experimenting with it. They are faster than the rest interface

**Comment by looselycoupled** [comment]
Thanks again although I'm just about to get into the Python bindings.  Looking forward to seeing the next release.
