### ISSUE TITLE
internal packages cannot be imported from within siblings

### ISSUE THREAD

**Issue by mako-taco** [SoftwareDefinedBuildings/btrdb#20]
Since go 1.6, this causes an error when building.

See https://golang.org/cmd/go/#hdr-Internal_Directories

**Comment by immesys** [comment]
This is likely because your build directories are set up incorrectly (so are attempting to access from unintended locations). I support go 1.6 and do not get this when building:

```
immesys@bunker:~/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/btrdbd$ go version
go version go1.6 linux/amd64
immesys@bunker:~/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/btrdbd$ go build -a
immesys@bunker:~/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/btrdbd$ 
```

Can you detail exactly what you are seeing?

**Comment by immesys** [comment]
If, for example you cloned btrdb outside your GOPATH, this would bite you...

**Comment by mako-taco** [comment]
Yeah, sorry. This is totally incorrect.
