### ISSUE TITLE
Help with comparison table details

### ISSUE THREAD

**Issue by sacreman** [SoftwareDefinedBuildings/btrdb#27]
Hi, I have a table listing open source time series database that I've been collaborating on with some other people who are interested in this subject.

With BtrDB being so new there isn't a lot of information about it. Any chance someone could click the cells and leave some comments for key items like average bytes used per data point stored on disk after compression?

Also, other benchmarks for databases have been done without batching. For example the DalmatinerDB benchmark was setup across three Joyent servers. Two of the servers used to generate the metrics and the 3rd running a copy of the database

https://gist.github.com/sacreman/b77eb561270e19ca973dd5055270fb28

This simulates a more real world scenario where metrics are sent over the network with no batching at all. Batching in memory would inflate the Dalmatiner numbers significantly.

If you could let me know ballpark figures for metrics per second on similar hardware under similar test criteria I'll update the fields.

It would also be good to understand how the clustering works. MongoDB for the metadata and Ceph for the storage are easy to figure out, but how does the BtrDB layer cluster? Can you simply add nodes with everything running to scale out? Also is it configurable with a certain number of replicas of data kept in memory for redundancy.

Lots of questions. Apologies for asking them all as I know you're not released yet, but I got a bit excited :)

**Comment by immesys** [comment]
I will try and publish a whitepaper soon with comparisons to popular databases. I haven't worked with DalmatinerDB before but I will add it to the list of databases. Thanks
