### ISSUE TITLE
Java and .Net Bindings

### ISSUE THREAD

**Issue by sirinath** [SoftwareDefinedBuildings/btrdb#29]
Wondering if you can add Java and .Net binds?

**Comment by immesys** [comment]
I will add support for Java and. Net in v4, thank you for your suggestion.

**Comment by mateuszlewko** [comment]
Hi, 
I see that v4 is done, but I couldn't find any library for .Net.
How can I use this great database with .net? 

Thanks!

**Comment by immesys** [comment]
We use GRPC to connect to the database, so you should be able to autogenerate bindings in the language of your choice using `https://github.com/SoftwareDefinedBuildings/btrdb/blob/master/grpcinterface/btrdb.proto`

**Comment by immesys** [comment]
Although actually, I think this will require the API frontend that has not yet been released.
