### ISSUE TITLE
Unexpected (very) short read

### ISSUE THREAD

**Issue by jf87** [SoftwareDefinedBuildings/btrdb#30]
I get this panic whenever I want to read/write to btrdb.
Reads/writes happen through giles2.
Any ideas on this?
I already updated both giles and btrdb to the most recent version.
It started when I moved my database files to a new drive, but this problem persists when I use my original drive.

Cheers!
Jonathan

`2016/09/27 11:23:28 cpinterface.go:59 ▶^[[0m cpnp connection
2016/09/27 11:23:32 ^[[35mfileprovider.go:225 ▶^[[0m Unexpected (very) short read
panic: Unexpected (very) short read

goroutine 35 [running]:
panic(0x833100, 0xc8200f4a10)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/op/go-logging.(_Logger).Panic(0xc8200589c0, 0xc8200f4980, 0x1, 0x1)
        /home/jofu/go/src/github.com/op/go-logging/logger.go:188 +0xc8
github.com/SoftwareDefinedBuildings/btrdb/internal/fileprovider.(_FileStorageProvider).Read(0xc82004ccb0, 0xc8203a6048, 0x10, 0x5b8, 0x36400004255f6b3, 0xc8203e2000, 0x5007, 0x5007, 0x0, 0x0, ...)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/internal/fileprovider/fileprovider.go:225 +0x3ba
github.com/SoftwareDefinedBuildings/btrdb/internal/bstore.(_BlockStore).ReadDatablock(0xc82007c120, 0xc8203a6048, 0x10, 0x5b8, 0x36400004255f6b3, 0x11dd4, 0x38, 0xf000000000000000, 0x0, 0x0)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/internal/bstore/blockstore.go:308 +0x19c
github.com/SoftwareDefinedBuildings/btrdb/qtree.(_QTree).LoadNode(0xc8200f8630, 0x36400004255f6b3, 0x11dd4, 0x538, 0xf000000000000000, 0xc8200f8600, 0x0, 0x0)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/qtree/qtree_utils.go:120 +0xbb
github.com/SoftwareDefinedBuildings/btrdb/qtree.NewReadQTree(0xc82007c120, 0xc8203a6048, 0x10, 0x5b8, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/qtree/qtree_utils.go:187 +0x165
github.com/SoftwareDefinedBuildings/btrdb.(_Quasar).QueryValuesStream(0xc8200129b0, 0xc8203a6048, 0x10, 0x5b8, 0x147822aee5ce5355, 0x147823c64b68efbc, 0xffffffffffffffff, 0xc8200f8240, 0x20, 0x0)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/quasar.go:194 +0x5a
github.com/SoftwareDefinedBuildings/btrdb/cpinterface.(_CPInterface).dispatchCommands.func1(0xc8200f8240, 0xc820119f28, 0x7f845e403bb0, 0xc820021108, 0xc8200129b0, 0x0, 0x0)
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/cpinterface/cpinterface.go:94 +0xa12
created by github.com/SoftwareDefinedBuildings/btrdb/cpinterface.(*CPInterface).dispatchCommands
        /home/jofu/go/src/github.com/SoftwareDefinedBuildings/btrdb/cpinterface/cpinterface.go:441 +0x475
`

**Comment by immesys** [comment]
Unfortunately that means that your database is corrupt. It is trying to read an address that is beyond the database files. Something bad must have happened while moving the files. You can remove a few superblocks from the offending streams to roll back

**Comment by jf87** [comment]
Thanks, I already expected something in that direction.
How do I remove the last superblocks?

**Comment by immesys** [comment]
In v4 this situation should not be possible, so I am closing this for now
