### ISSUE TITLE
Issue in Statistical Queries

### ISSUE THREAD

**Issue by samkumar99** [SoftwareDefinedBuildings/btrdb#9]
As documented in interface.capnp, the End Time on statistical queries is exclusive. However, the database in reality may include a record whose start time is equal to the end time of a query.

For an example of this, run the quasarloadgenerator in insert mode (commit fedc74a1d741deeea0b9348584358fd60783b593) with the following config file:

<pre><code>
TOTAL_RECORDS=16777216
TCP_CONNECTIONS=3
POINTS_PER_MESSAGE=4096
NANOS_BETWEEN_POINTS=1048576
MAX_TIME_RANDOM_OFFSET=1048575
FIRST_TIME=1420582217226125312
NUM_SERVERS=1
DB_ADDR1=localhost:4410
NUM_STREAMS=1
UUID1=9f67541c-95ee-11e4-a7ac-0026b6df9cf2
MAX_CONCURRENT_MESSAGES=4
RAND_SEED=15
PERM_SEED=0
DETERMINISTIC_KV=false
GET_MESSAGE_TIMES=false
STATISTICAL_PW=27
</code></pre>

To see the bug, run it in verify mode. Or, decrease TOTAL_RECORDS to 4096, and the program will receive 4224 points because it received an extra record that contains 128 points.

Interestingly, this problem only shows up when the Cap'n Proto interface is used. The HTTP interface gives proper results.

**Comment by immesys** [comment]
Good find. I award you +2 internets.

**Comment by immesys** [comment]
I believe this is similar to the spurious -1 thing? Please add a unit test to github.com/go-btrdb/btrdb v4
